### ISSUE TITLE
Feature request: emojis

### ISSUE THREAD

**Issue by carodew** [18F/charlie#144]
No self respecting slackbot is complete without emojis. 

For example, the Thanksgiving notice could have a 🦃 or 🍂attached. 

pls and thx bbye 

(srsly tho this is awesome)

**Comment by mgwalker** [comment]
@carodew Can you say more about this?  Is this in reference to #143?  (I just want to make sure I understand the ask!  😄)

**Comment by carodew** [comment]
@mgwalker Yes! Didn't realize this was a broader project so apologies for any confusion. 

Also feel free to ignore, but holidays seem like they could use a little extra 🎉

**Comment by mgwalker** [comment]
@carodew I still think this is a great idea!  Would you be game for recommending emoji for some/all of the holidays?  Here's the list:

- New Year's Day
- Birthday of Martin Luther King, Jr.
- Washington's Birthday
- Memorial Day
- Independence Day
- Labor Day
- Columbus Day
- Veterans Day
- Thanksgiving Day 🦃
- Christmas Day

**Comment by tbaxter-18f** [comment]
Some suggestions:
Christmas: 🎄 
Veteran's day: :salute-you:
Labor day: :department-of-labor: or 💪 
Independence day: 🎆 
memorial day: :salute-you: (although I wonder about differentiating with veteran's day)
Washington: :george:
MLK:  I don't think we have anything yet
New year: :baby-new-year:

Columbus doesn't get one. Because _that_ guy

**Comment by mgwalker** [comment]
What about :ohio: for Columbus Day?
