### ISSUE TITLE
Inclusion/guys bot changes

### ISSUE THREAD

**Issue by mgwalker** [18F/charlie#209]
### Goals and implementation ideas

* Be gentle and fun
  - add more "did you mean" responses, in addition to `y'all`
  - **done** ~consider changes to the language the bot uses when responding, including the blog post unfurl title and summary~
  - ignore messages that say "guys bot" or "guysbot", because to quote @nkkl, "talking about the bot itself is clearly not the same as casually saying the g-word"
* Reduce traffic in chat channels
  - **done** ~send ephemeral messages only to the user who triggered the bot, not to the whole channel~
  - **done** ~mark triggering messages with the `:thumbsup_all:` emoji to indicate that the bot has responded~
* Don't trigger in partner channels
  - ignore messages from channels where the name begins with `partners-`
  - alternatively, only trigger on messages from users who are ***full*** users, not single- or multi-channel users

**Comment by annepetersen** [comment]
I think

> mark triggering messages with the :thumbsup_all: emoji to indicate that the bot has responded

might infer the bot is approving of the message. Might consider some other emoji instead?

**Comment by awichman** [comment]
Suggested updates for response text:

Did you mean **[replacement word]**? _([What's this?](https://web.archive.org/web/20170714141744/https://18f.gsa.gov/2016/01/12/hacking-inclusion-by-customizing-a-slack-bot/))_
Hello! Our inclusive TTS culture is built one interaction at a time, and inclusive language is the foundation. Instead of guys, we encourage everyone to try out  a new phrase to describe multiple people. This is a small way we build inclusion into our everyday work lives.

@annepetersen Thanks so much for raising that issue! Yes, let's choose a different emoji. Maybe :hubot: is good for this purpose (and serves as a visual cue/reminder to others about the bot, even though they aren't seeing the message?).

**Comment by awichman** [comment]
@mgwalker we have a new :inclusion-bot: emoji for the response 👍

**Comment by mgwalker** [comment]
The Inclusion bot will never be done, but I think the major goals of this issue have been resolved. ❤️
