### ISSUE TITLE
move to Slack App

### ISSUE THREAD

**Issue by afeld** [18F/charlie#235]
Charlie is set up through [an old-style Slack integration](https://gsa-tts.slack.com/services/BLZ2U7N4E). I created [a Slack App for the `TTS Inspector`](https://api.slack.com/apps/A01B3MX46JC), which is Slack's newer/preferred way of getting tokens etc. Probably makes sense to consolidate the former into the latter. [More information.](https://slack.dev/hubot-slack/#getting-a-slack-token)

## Acceptance criteria

- [x] Charlie is leveraging the new/supported method for registering integrations with Slack

**Comment by mgwalker** [comment]
Unfortunately, it turns out that the [Slack real-time messaging API](https://api.slack.com/rtm) does not work with new-style apps. Charlie relies on that API in order to be able to respond to commands/comments.

**Comment by afeld** [comment]
Looks like the [Events API](https://api.slack.com/events-api) may be the successor?

**Comment by mgwalker** [comment]
Yes. And that raises two issues:
1. Hubot uses the RTM API, so we'd have to also migrate away from Hubot (to maybe something like [Bolt](https://slack.dev/bolt-js/tutorial/hubot-migration)), which might be more of a lift?
2. The Events API requires an open HTTP port, which would be new. The RTM API uses an outgoing websocket rather than having the bot listen for events. I've always been nervous about having open ports on Charlie, but if that's something you're comfortable with, then okay! 😄

**Comment by mgwalker** [comment]
Closed by #255
