### ISSUE TITLE
Include memes such as Karen in Inclusion Bot

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [18F/charlie#314]
## Background Information

The problem we're trying to solve is that there is a popular meme that references to white women who appear angry and show bias towards people in an irrational seeming way as the name "Karen" and that has now been adopted as basically a slur, so people call other will reference others as "Karen" in reference to that meme, but in reality, it can be exclusionary to all of the women named Karen who do not represent and portray the behaviors present in the meme. 

## Implementation Steps

- [ ] 

## Acceptance Criteria

- [ ] The inclusion bot picks up when Karen is used in a meme-sort of way and triggers

**Comment by mgwalker** [comment]
This has been open for a while, and I want us to move on it. I recommend bringing it to the diversity guild for a further discussion about what we want to do (I'm happy to do that), and also to TTS engineers to think about what's even possible here. With that in mind, some notes:

1. This has happened in TTS Slack a few times in the past couple of years, so it's not hypothetical. However, the way it happened was only distinguishable as the meme-ified version by surrounding context, so the bot wouldn't be able to differentiate between someone talking about Karen and using it as the "angry white Karen" meme. I think if we want to implement this, we'd need some good brainstorming between designers and engineers to figure out exactly what to look for in messages. Otherwise we'd end up with a ton of false-positives.

2. I agree with the intent of this PR. I do want to note, though, that the "Karen" meme originated in response to the weaponization of white privilege, especially against people of color but also often against people of lesser means. It absolutely picked up sexist connotations from there, and using a real name is also... harmful. I think it's awesome if we want to encourage people to be mindful about the real Karens who do not embody the "Karen" meme, and use other ways of denouncing white supremacy, as long as we remember that the person using the "Karen" meme might very well have good intentions and what we're trying to accomplish is nudging them towards a meme that has the same intentions but without causing collateral harm. (If someone is using the "Karen" meme in a sexist way, that is a different story altogether.)

**Comment by mgwalker** [comment]
This is now in the [diversity guild Slack channel](https://gsa-tts.slack.com/archives/C02DJFR0V/p1652973706408229) for folks who want to follow or join the discussion there!

**Comment by mgwalker** [comment]
Closing this issue since it doesn't seem to be able to get any traction with the diversity guild.
